name: Windows PR Check

on:
  pull_request:
    branches:
      - main  # or any target branch for PRs

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (Windows)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # change based on your needs

      - name: Install dependencies (Windows)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (Windows)
        run: python hello.py 
