name: PR Checks (Windows)

on:
  pull_request:
    branches:
      - main  # or your default branch like 'master'

jobs:
  build:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # change as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python hello.py  # or any other test framework you use
